SELECT C.CAR_TYPE, COUNT(*) AS CARS
FROM (SELECT *
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE OPTIONS
          LIKE '%통풍시트%'
         OR OPTIONS
          LIKE '%열선시트%'
         OR OPTIONS
          LIKE '%가죽시트%') AS C
GROUP BY C.CAR_TYPE
ORDER BY C.CAR_TYPE ASC;