SELECT C.CAR_ID, 
CASE
WHEN SUM(IS_RENT) >= 1 THEN '대여중'
WHEN SUM(IS_RENT) = 0 THEN '대여 가능'
END AS AVAILABILITY
FROM
(SELECT CAR_ID,
    CASE
        WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
        ELSE 0
    END AS IS_RENT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) C
GROUP BY C.CAR_ID
ORDER BY CAR_ID DESC;