SELECT DISTINCT(car.car_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history ON car.CAR_ID = history.CAR_ID
AND MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC